### ISSUE TITLE
Terraform fails with  error - no matching VPC found

### ISSUE THREAD

**Issue by superyarick** [mitre/demo-aws-hardening#1]
```
       data.aws_vpc.default: Refreshing state...
       
       Error: Error refreshing state: 1 error(s) occurred:
       
       * data.aws_vpc.default: 1 error(s) occurred:
       
       * data.aws_vpc.default: data.aws_vpc.default: no matching VPC found
```

**Comment by nithish516** [comment]
Is this issue resolved ? I'm facing similar issue. I'm unable to find the solution in any blogs

**Comment by superyarick** [comment]
@nithish516 - terraform is complaining about the type or lack of the default VPC configured in your AWS Account. I would suggest to check if you have all your environment variables set by running pre-kitchen.rb.  This will validate the environment.
